### ISSUE TITLE
Values still appear in GBP

### ISSUE THREAD

**Issue by yephny** [StarGW-net/stargw-fx#1]
Despite setting USD as my base currency, the app still shows all currencies in terms of GBP. I don't think it's a bug, as I can see their USD conversions in gray values. Though, I don't see why the app would still show me conversions based on GBP at all. i'd rather have the large number to be in USD, and the gray one the other way around (e.g. white: USD->EUR, gray: EUR->USD).

![usd](https://i.imgur.com/nvnbFKI.png)

**Comment by StarGW-net** [comment]
After setting your base currency to USD, you may need to set your USD value to 1, so you are comparing 1USD to other currencies. Hmmm, I should probably do this automatically when the base currency is changed. You can put a different value in base currency (and others) so you can do quick price compairons while on holiday.

**Comment by yephny** [comment]
That's pretty smart, thanks.
